quizz_question:
    resource:   "@QuizzBundle/Controller/Admin/QuestionController.php"
    type:       annotation

quizz_choice:
    resource:   "@QuizzBundle/Controller/Admin/ChoiceController.php"
    type:       annotation
